### ISSUE TITLE
kubectl command unable to execute

### ISSUE THREAD

**Issue by schristoff** [getporter/kubernetes-mixin#54]
Problem:
mixin seems to be having issues running kubectl commands even after seeing credential set. i can see it's pulling the address from my kubeconfig (see `127.0.0.1:64084`) and kubectl runs fine outside of porter

recreation steps:
step 1 & 2 of https://getporter.org/operator/quickstart/
I create a kind cluster, and set kind context. When setting the kubeconfig I set it as a filepath with my full path, not relative. 

here's some output:

```
docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS                       NAMES
   mongo:4.0-xenial       "docker-entrypoint.s…"   4 minutes ago   Up 4 minutes   0.0.0.0:27018->27017/tcp    porter-mongodb-docker-plugin
   kindest/node:v1.26.3   "/usr/local/bin/entr…"   15 hours ago    Up 6 minutes   127.0.0.1:64084->6443/tcp   kind-control-plane
```

kubeconfig
```

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:==
    server: https://127.0.0.1:63373
  name: kind-new-cluster
- cluster:
    certificate-authority-data: 
    server: https://127.0.0.1:64084
  name: kind-kind
contexts:
- context:
    cluster: kind-new-cluster
    user: kind-new-cluster
  name: kind-new-cluster
- context:
    cluster: kind-kind
    user: kind-kind
  name: kind-kind
current-context: kind-kind
```

```
porter install porterops -c porterops -r ghcr.io/getporter/porter-operator:v0.8.0

executing install action from porter-operator (installation: /porterops)
Set manager image reference
Setting manager image to ghcr.io/getporter/porter-operator@sha256:dd8d95c853738954781bc1dce62e66d74f51c12eb3aa6536843f268f6f740ec6
Apply operator manifests
The connection to the server 127.0.0.1:64084 was refused - did you specify the right host or port?
Error: error running command /cnab/app/usr/local/bin/kubectl apply -f manifests/operator.yaml --wait: exit status 1
1 error occurred:
	* mixin execution failed: package command failed /cnab/app/cnab/app/mixins/kubernetes/runtimes/kubernetes-runtime install
The connection to the server 127.0.0.1:64084 was refused - did you specify the right host or port?
Error: error running command /cnab/app/usr/local/bin/kubectl apply -f manifests/operator.yaml --wait: exit status 1



1 error occurred:
	* mixin execution failed: package command failed /cnab/app/cnab/app/mixins/kubernetes/runtimes/kubernetes-runtime install
The connection to the server 127.0.0.1:64084 was refused - did you specify the right host or port?
Error: error running command /cnab/app/usr/local/bin/kubectl apply -f manifests/operator.yaml --wait: exit status 1



1 error occurred:
	* container exit code: 1, message: <nil>
```

(locally, outside porter)
```
kubectl get pods -A
NAMESPACE            NAME                                         READY   STATUS    RESTARTS        AGE
kube-system          coredns-787d4945fb-2m99d                     1/1     Running   1 (7m37s ago)   14h
kube-system          coredns-787d4945fb-nw87v                     1/1     Running   1 (7m37s ago)   14h
kube-system          etcd-kind-control-plane                      1/1     Running   1 (7m37s ago)   14h
kube-system          kindnet-jnt5g                                1/1     Running   1 (7m37s ago)   14h
kube-system          kube-apiserver-kind-control-plane            1/1     Running   1 (7m37s ago)   14h
kube-system          kube-controller-manager-kind-control-plane   1/1     Running   1 (7m37s ago)   14h
kube-system          kube-proxy-xcd2h                             1/1     Running   1 (7m37s ago)   14h
kube-system          kube-scheduler-kind-control-plane            1/1     Running   1 (7m37s ago)   14h
local-path-storage   local-path-provisioner-75f5b54ffd-z9nkx      1/1     Running   1 (7m37s ago)   14h
```
